apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.tagetPort }}
      nodePort: {{ .Values.backend.service.nodePort }}
  selector:
    app: todo-backend
