version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: ddoddo-market-db-container
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: ddoddo_market_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: mirae2/ddoddo-market-backend:v1.0
    container_name: ddoddo-market-backend-container
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ddoddo_market_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: dev # 선택사항

volumes:
  postgres-data:
