backend:
  replicaCount: 2
  image:
<<<<<<< HEAD
    repository: mirae2/k8s-labs-todo-backend
=======
    repository: captainyun/k8s-labs-todo-backend
>>>>>>> f9c2a7ccf15662bc8aeda6614979715cc6fb813f
    tag: v1.0
  service:
    type: NodePort
    port: 8080
    targetPort: 8080
    nodePort:
      enabled: true
      port: 30001
  cors_allowed_origins: http://localhost:3000

database:
  name: tododb
  user: todouser
  password: "todo1234"
  rootPassword: "root1234"
