apiVersion: v1
kind: Pod
metadata:
  name: nginx-configmap-volume-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.20
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-conf-volume
          mountPath: /etc/nginx/conf.d #리눅스에서 설정 파일 보통 etc폴더에 존재 (마운트 포인트) - 파드 정보 자체가 여기에 저장됨?
  volumes:
    - name: nginx-conf-volume
      configMap:
        name: nginx-conf
